ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "jobStartOtp" TEXT;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "jobStartedAt" TIMESTAMP(3);
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "jobCompleteOtp" TEXT;
ALTER TABLE "bookings" ADD COLUMN IF NOT EXISTS "jobCompletedAt" TIMESTAMP(3);
